### ISSUE TITLE
Suggestion: change time delta computation

### ISSUE THREAD

**Issue by federicobond** [sesh/piprot#56]
Currently, `piprot` uses the difference between the specified version's release date and the latest version's release date, measured in days. For requirements that don't publish updates frequently, this means that when an update is eventually published, the number jumps dramatically.

I propose to use the difference between the latest version's release date and today instead, so if a project has published an update a week ago, it will show as 7 days old instead of possibly hundreds of days. For requirements that are up to date, the difference is still zero. 

I understand that a change like this affects substantially the semantics of the program, and can confuse current users, but I think it may be worthwhile to consider.

I would love to hear your thoughts on this.

**Comment by sesh** [comment]
@federicobond I've discussed this with others before, and while I'm open to the idea of _optionally_ calculating the total in a different way, I keep settling on keeping it the same.

Does it really make that much of a difference? The way we use piprot is to ensure that we know when packages we depend on are updated - the actual number of days doesn't really matter, just the fact that it's out of date.

**Comment by federicobond** [comment]
I agree with you in that it's not worth the additional complexity of *optionally* providing an alternative calculation.

The thing is, as it stands, the number does not communicate anything meaningful. One day it can be zero and the next over a thousand because an old package released a new version. For a project with 3 dependencies, if you were up-to-date yesterday, at most you should be 3 days outdated today.

**Comment by gdub** [comment]
I believe the current calculation is misleading in two ways:

1. As @federicobond suggests, if a new version of a requirement is available, you can only be as out of date as the version that was released following your current version.  For example, if I'm on version 1.0, and there have since been a 1.1 and a 2.0 release, then the out-of-date time would be from the release date of 1.1 to today.
2. If I have multiple out-of-date requirements, then I can only be as out of date as the oldest out-of-date requirement, not the combined total days of all the out-of-date requirements.  For example, if requirement A is one day out of date, and requirement B is two days out of date, then overall I should be two days out of date, not three.  Two days ago I was fully up-to-date.

IMHO, with the two points above addressed, the "days out of date" information becomes something more meaningful.  This would do away with the dramatic jumps for packages with few releases, as well as the exponential rise with each additional out-of-date requirement.

**Comment by SamuelMS** [comment]
I agree with @federicobond and @gdub. I'd be happy to submit a PR to update the delta calculation.
